### PR TITLE
fix: Readme.md image not loading issue.

### PR DESCRIPTION
**Pull request by faizan1191**
Readme.md Crowdin logo image not loading on coming back after viewing any file. Similar issue in another repo https://github.com/crowdin/crowdin-api-client-php/issues/164

Screenshot (4)

### CODE REVIEW

**Review by andrii-bodnar — APPROVED** [review]
@faizan1191 thank you!

**Comment by faizan1191** [comment]
@andrii-bodnar can you please mark this PR as hacktoberfest accepted??

**Comment by andrii-bodnar** [comment]
@faizan1191 done

**Comment by faizan1191** [comment]
@andrii-bodnar thanks

**Pull request merged**
