### PR TITLE
Fix LanguagesModel dialectOf type

### PR DESCRIPTION
**Pull request by jackassmc**
Fixes https://github.com/crowdin/crowdin-api-client-js/issues/179

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
Hi @jackassmc, thanks a lot for your contribution! 🎉

**Comment by jackassmc** [comment]
Hi @andrii-bodnar, my pleasure :)

Could you please share when the next release is planned?

**Comment by andrii-bodnar** [comment]
@jackassmc the new version will be available in 10-20 minutes

**Comment by jackassmc** [comment]
Fantastic, thank you!

**Comment by andrii-bodnar** [comment]
@jackassmc we are experiencing some issues with the deployment, I will let you know when it will be available, sorry for the inconvenience

**Comment by jackassmc** [comment]
@andrii-bodnar no worries, thanks for the heads up.

**Comment by andrii-bodnar** [comment]
@jackassmc now it's available - [1.18.2](https://www.npmjs.com/package/@crowdin/crowdin-api-client/v/1.18.2)

**Comment by jackassmc** [comment]
Thanks again!

**Pull request merged**
