### PR TITLE
Created Dependabot.yml

### PR DESCRIPTION
**Pull request by jenistenxavier**
Added Dependabot configuration to automatically check for updates on packages on a weekly basis. It will also create a PR whenever there is an update.

Link to issue this resolves
Fixes: https://github.com/crowdin/crowdin-api-client-js/issues/192

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
@jenistenxavier looks good to me, thanks a lot for your contribution!

**Review by andrii-bodnar — APPROVED** [review]

**Comment by andrii-bodnar** [comment]
@jenistenxavier an error have occurred - https://github.com/crowdin/crowdin-api-client-js/runs/9136375105

Please take a look

**Comment by jenistenxavier** [comment]
@andrii-bodnar : Sure. checking it now.

**Comment by jenistenxavier** [comment]
@andrii-bodnar : Please try this. Let me know if it shows issues again. 
PR - https://github.com/crowdin/crowdin-api-client-js/pull/194
Screenshot 2022-10-26 at 1 08 48 AM

**Comment by andrii-bodnar** [comment]
@jenistenxavier why do I need to setup this token?

**Pull request merged**
